server:
  port: 8082

spring:
  application:
    name: eureka-client-blog

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

swagger:
  base-package: com.cloud.eureka.client.controller